# Generated by Django 2.1.4 on 2019-02-09 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(default='')),
                ('questionTitle', models.TextField(default='')),
                ('accuracy', models.IntegerField(default=0)),
                ('submission', models.IntegerField(default=0)),
                ('all_submissions', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.TextField()),
                ('subtime', models.CharField(default='', max_length=10)),
                ('testCaseScore', models.IntegerField(default=0)),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_score', models.IntegerField(default=0)),
                ('totalScore', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('option', models.CharField(default='c', max_length=3)),
                ('level', models.CharField(max_length=10)),
                ('QuestionDetails', models.ManyToManyField(to='basic_app.Questions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
