# Generated by Django 2.1.4 on 2019-02-18 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qid', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='temp_score',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='uacsubtime',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub',
            field=models.TextField(null=True),
        ),
    ]
