# Generated by Django 2.1.4 on 2019-02-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email1',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email2',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='uacsubtime',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub',
            field=models.TextField(null=True),
        ),
    ]
