# Generated by Django 2.1.4 on 2019-02-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190216_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='temp_score',
            new_name='score',
        ),
    ]
