# Generated by Django 2.1.4 on 2019-02-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190218_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='QuestionDetails',
        ),
    ]
