# Generated by Django 2.1.4 on 2019-02-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20190222_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
