# Generated by Django 2.1.4 on 2019-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_submissions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='latestAcQid',
            field=models.IntegerField(default=1),
        ),
    ]
