# Generated by Django 2.1.4 on 2019-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_userprofileinfo_latestacqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
